package view;

import beans.Fornecedores;
import dao.FornecedoresDao;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class TelaFornecedores extends javax.swing.JFrame {

    /**
     * Creates new form TelaFornecedores
     */
    public TelaFornecedores() {
        initComponents();
        listarTodosFornecedores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlGeral = new javax.swing.JPanel();
        pnlTitle = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        tabbedPaneFornecedores = new javax.swing.JTabbedPane();
        pnlDadosFornecedores = new javax.swing.JPanel();
        lblId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        btnPesquisarNome = new javax.swing.JButton();
        lblCep = new javax.swing.JLabel();
        txtCep = new javax.swing.JTextField();
        lblCelular = new javax.swing.JLabel();
        txtCelular = new javax.swing.JTextField();
        lblUf = new javax.swing.JLabel();
        cmbxUf = new javax.swing.JComboBox<>();
        lblEndereco = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        lblBairro = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        lblNumero = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        lblCidade = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        lblComplemento = new javax.swing.JLabel();
        txtComplemento = new javax.swing.JTextField();
        lblCnpj = new javax.swing.JLabel();
        txtCnpj = new javax.swing.JTextField();
        pnlConsultaFornecedores = new javax.swing.JPanel();
        lblNomeFornecedor = new javax.swing.JLabel();
        txtNomeFornecedor = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        scrollPaneDadosFornecedores = new javax.swing.JScrollPane();
        tblDadosFornecedores = new javax.swing.JTable();
        btnCadastrar = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlGeral.setBackground(new java.awt.Color(248, 248, 255));
        pnlGeral.setLayout(new java.awt.GridBagLayout());

        pnlTitle.setBackground(new java.awt.Color(215, 189, 226));

        lblTitle.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Área de Fornecedores");

        javax.swing.GroupLayout pnlTitleLayout = new javax.swing.GroupLayout(pnlTitle);
        pnlTitle.setLayout(pnlTitleLayout);
        pnlTitleLayout.setHorizontalGroup(
            pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTitleLayout.createSequentialGroup()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 678, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlTitleLayout.setVerticalGroup(
            pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTitleLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblTitle)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        pnlGeral.add(pnlTitle, gridBagConstraints);

        tabbedPaneFornecedores.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        tabbedPaneFornecedores.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        pnlDadosFornecedores.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblId.setText("ID:");
        pnlDadosFornecedores.add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 20, -1, -1));

        txtId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtId.setEnabled(false);
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdtxtIdActionPerformed(evt);
            }
        });
        pnlDadosFornecedores.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 48, -1));

        lblNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNome.setText("Nome:");
        pnlDadosFornecedores.add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        txtNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pnlDadosFornecedores.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 307, -1));

        lblEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEmail.setText("Email:");
        pnlDadosFornecedores.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 100, -1, -1));

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pnlDadosFornecedores.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 307, -1));

        btnPesquisarNome.setBackground(new java.awt.Color(255, 218, 185));
        btnPesquisarNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPesquisarNome.setText("Pesquisar");
        btnPesquisarNome.setToolTipText("Clique neste botão para pesquisar um fornecedor pelo nome");
        btnPesquisarNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarNomeActionPerformed(evt);
            }
        });
        pnlDadosFornecedores.add(btnPesquisarNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 104, -1));

        lblCep.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCep.setText("Cep:");
        pnlDadosFornecedores.add(lblCep, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 140, -1, -1));

        txtCep.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pnlDadosFornecedores.add(txtCep, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 101, -1));

        lblCelular.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCelular.setText("Celular:");
        pnlDadosFornecedores.add(lblCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 140, -1, -1));

        txtCelular.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pnlDadosFornecedores.add(txtCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 102, -1));

        lblUf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblUf.setText("UF:");
        pnlDadosFornecedores.add(lblUf, new org.netbeans.lib.awtextra.AbsoluteConstraints(522, 140, -1, -1));

        cmbxUf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Selecione-", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        cmbxUf.setToolTipText("Selecione uma unidade federal");
        pnlDadosFornecedores.add(cmbxUf, new org.netbeans.lib.awtextra.AbsoluteConstraints(547, 140, 100, -1));

        lblEndereco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEndereco.setText("Endereço:");
        pnlDadosFornecedores.add(lblEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        txtEndereco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pnlDadosFornecedores.add(txtEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 181, 277, -1));

        lblBairro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblBairro.setText("Bairro:");
        pnlDadosFornecedores.add(lblBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(487, 180, -1, -1));

        txtBairro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pnlDadosFornecedores.add(txtBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(532, 180, 115, -1));

        lblNumero.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNumero.setText("N°:");
        pnlDadosFornecedores.add(lblNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 180, -1, -1));
        pnlDadosFornecedores.add(txtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 181, 55, -1));

        lblCidade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCidade.setText("Cidade:");
        pnlDadosFornecedores.add(lblCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 222, -1, -1));

        txtCidade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pnlDadosFornecedores.add(txtCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 130, -1));

        lblComplemento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblComplemento.setText("Complemento:");
        pnlDadosFornecedores.add(lblComplemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 222, -1, -1));

        txtComplemento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtComplemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtComplementoActionPerformed(evt);
            }
        });
        pnlDadosFornecedores.add(txtComplemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 219, 134, -1));

        lblCnpj.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCnpj.setText("CNPJ:");
        pnlDadosFornecedores.add(lblCnpj, new org.netbeans.lib.awtextra.AbsoluteConstraints(487, 222, -1, -1));

        txtCnpj.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pnlDadosFornecedores.add(txtCnpj, new org.netbeans.lib.awtextra.AbsoluteConstraints(527, 219, 120, -1));

        tabbedPaneFornecedores.addTab("Dados da empresa", pnlDadosFornecedores);

        lblNomeFornecedor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNomeFornecedor.setText("Nome do cliente:");

        txtNomeFornecedor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnPesquisar.setBackground(new java.awt.Color(255, 218, 185));
        btnPesquisar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.setToolTipText("Clique neste botão para filtrar um fornecedor pelo nome");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        tblDadosFornecedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Email", "Cnpj", "Cep", "Endereço", "N°", "Bairro", "Cidade", "UF", "Celular"
            }
        ));
        scrollPaneDadosFornecedores.setViewportView(tblDadosFornecedores);

        javax.swing.GroupLayout pnlConsultaFornecedoresLayout = new javax.swing.GroupLayout(pnlConsultaFornecedores);
        pnlConsultaFornecedores.setLayout(pnlConsultaFornecedoresLayout);
        pnlConsultaFornecedoresLayout.setHorizontalGroup(
            pnlConsultaFornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConsultaFornecedoresLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pnlConsultaFornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPaneDadosFornecedores, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlConsultaFornecedoresLayout.createSequentialGroup()
                        .addComponent(lblNomeFornecedor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNomeFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlConsultaFornecedoresLayout.setVerticalGroup(
            pnlConsultaFornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConsultaFornecedoresLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(pnlConsultaFornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeFornecedor)
                    .addComponent(txtNomeFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollPaneDadosFornecedores, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabbedPaneFornecedores.addTab("Consulta de fornecedores", pnlConsultaFornecedores);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 0, 0);
        pnlGeral.add(tabbedPaneFornecedores, gridBagConstraints);

        btnCadastrar.setBackground(new java.awt.Color(179, 229, 252));
        btnCadastrar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.setToolTipText("Clique neste botão para cadastrar um fornecedor");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 51, 13, 0);
        pnlGeral.add(btnCadastrar, gridBagConstraints);

        btnAtualizar.setBackground(new java.awt.Color(179, 229, 252));
        btnAtualizar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAtualizar.setText("Atualizar");
        btnAtualizar.setToolTipText("Clique neste botão para atualizar o registro de um fornecedor");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 25;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 50, 13, 0);
        pnlGeral.add(btnAtualizar, gridBagConstraints);

        btnExcluir.setBackground(new java.awt.Color(179, 229, 252));
        btnExcluir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setToolTipText("Clique neste botão para excluir o registro de um fornecedor");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 38;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 60, 13, 0);
        pnlGeral.add(btnExcluir, gridBagConstraints);

        btnLimpar.setBackground(new java.awt.Color(179, 229, 252));
        btnLimpar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.setToolTipText("Clique neste botão para limpar os campos");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 28;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 50, 13, 0);
        pnlGeral.add(btnLimpar, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlGeral, javax.swing.GroupLayout.PREFERRED_SIZE, 678, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlGeral, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdtxtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdtxtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdtxtIdActionPerformed

    private void txtComplementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtComplementoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtComplementoActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        try {
            if (txtNome.getText().trim().isEmpty() || txtCnpj.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Nome e CNPJ são obrigatórios!");
                return;
            }

            Fornecedores fornecedor = new Fornecedores();

            fornecedor.setNome(txtNome.getText());
            fornecedor.setCnpj(txtCnpj.getText());
            fornecedor.setEmail(txtEmail.getText());
            fornecedor.setCelular(txtCelular.getText());
            fornecedor.setCep(txtCep.getText());
            fornecedor.setEndereco(txtEndereco.getText());
            fornecedor.setNumero(txtNumero.getText());
            fornecedor.setBairro(txtBairro.getText());
            fornecedor.setCidade(txtCidade.getText());
            fornecedor.setComplemento(txtComplemento.getText());
            fornecedor.setUnidade(cmbxUf.getSelectedItem().toString());

            FornecedoresDao fornecedoresDao = new FornecedoresDao();
            fornecedoresDao.cadastroFornecedores(fornecedor);

            listarTodosFornecedores();

            JOptionPane.showMessageDialog(null, "Fornecedor cadastrado com sucesso!");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Não foi possível cadastrar o fornecedor: " + e.getMessage());
            e.printStackTrace();
        }

    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        try {
            if (txtNome.getText().trim().isEmpty() || txtCnpj.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Nome e CNPJ são obrigatórios!");
                return;
            }

            Fornecedores fornecedor = new Fornecedores();

            fornecedor.setId(Integer.parseInt(txtId.getText()));
            fornecedor.setNome(txtNome.getText());
            fornecedor.setCnpj(txtCnpj.getText());
            fornecedor.setEmail(txtEmail.getText());
            fornecedor.setCelular(txtCelular.getText());
            fornecedor.setCep(txtCep.getText());
            fornecedor.setEndereco(txtEndereco.getText());
            fornecedor.setNumero(txtNumero.getText());
            fornecedor.setBairro(txtBairro.getText());
            fornecedor.setCidade(txtCidade.getText());
            fornecedor.setComplemento(txtComplemento.getText());
            fornecedor.setUnidade(cmbxUf.getSelectedItem().toString());

            FornecedoresDao fornecedoresDao = new FornecedoresDao();
            fornecedoresDao.atualizarFornecedores(fornecedor);

            listarTodosFornecedores();

            JOptionPane.showMessageDialog(null, "Fornecedor atualizado com sucesso!");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Não foi possível atualizar o fornecedor: " + e.getMessage());
            e.printStackTrace();
        }

    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnPesquisarNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarNomeActionPerformed
        try {
            String nome = txtNome.getText().trim();

            if (nome.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Digite o nome do fornecedor para pesquisar.");
                return;
            }

            FornecedoresDao dao = new FornecedoresDao();
            Fornecedores fornecedor = dao.buscarNomeFornecedor(nome);

            if (fornecedor != null) {
                txtId.setText(String.valueOf(fornecedor.getId()));
                txtNome.setText(fornecedor.getNome());
                txtCnpj.setText(fornecedor.getCnpj());
                txtEmail.setText(fornecedor.getEmail());
                txtCelular.setText(fornecedor.getCelular());
                txtCep.setText(fornecedor.getCep());
                txtEndereco.setText(fornecedor.getEndereco());
                txtNumero.setText(fornecedor.getNumero());
                txtBairro.setText(fornecedor.getBairro());
                txtCidade.setText(fornecedor.getCidade());
                txtComplemento.setText(fornecedor.getComplemento());
                cmbxUf.setSelectedItem(fornecedor.getUnidade());

                JOptionPane.showMessageDialog(null, "Fornecedor encontrado!");
            } else {
                JOptionPane.showMessageDialog(null, "Fornecedor não encontrado!");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao buscar fornecedor: " + e.getMessage());
            e.printStackTrace();
        }

    }//GEN-LAST:event_btnPesquisarNomeActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        try {
            if (txtId.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Pesquise um fornecedor antes de excluir.");
                return;
            }

            int confirmacao = JOptionPane.showConfirmDialog(
                    null,
                    "Tem certeza que deseja excluir este fornecedor?",
                    "Confirmação",
                    JOptionPane.YES_NO_OPTION
            );

            if (confirmacao == JOptionPane.YES_OPTION) {
                Fornecedores fornecedor = new Fornecedores();
                fornecedor.setId(Integer.parseInt(txtId.getText())); // este id foi o id preenchido na pesquisa

                FornecedoresDao dao = new FornecedoresDao();
                dao.excluirFornecedores(fornecedor);

                listarTodosFornecedores();

                JOptionPane.showMessageDialog(null, "Fornecedor excluído com sucesso!");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao excluir fornecedor: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // Limpar todos os campos
        txtId.setText("");
        txtNome.setText("");
        txtCnpj.setText("");
        txtEmail.setText("");
        txtCelular.setText("");
        txtCep.setText("");
        txtEndereco.setText("");
        txtNumero.setText("");
        txtBairro.setText("");
        txtCidade.setText("");
        txtComplemento.setText("");
        cmbxUf.setSelectedIndex(0);
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        try {
            // Pega o nome digitado no jTextField
            String nome = txtNomeFornecedor.getText().trim();

            // Buscando o fornecedor pelo nome
            FornecedoresDao dao = new FornecedoresDao();
            ArrayList<Fornecedores> lista = dao.listarFornecedoresPorNome(nome);

            // Atualiza a tabela com os resultados encontrados
            DefaultTableModel modelo = (DefaultTableModel) tblDadosFornecedores.getModel();
            modelo.setRowCount(0);

            for (Fornecedores f : lista) {
                modelo.addRow(new Object[]{
                    f.getId(),
                    f.getNome(),
                    f.getEmail(),
                    f.getCnpj(),
                    f.getCep(),
                    f.getEndereco(),
                    f.getNumero(),
                    f.getBairro(),
                    f.getCidade(),
                    f.getUnidade(),
                    f.getCelular()
                });
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao pesquisar fornecedor: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnPesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaFornecedores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnPesquisarNome;
    private javax.swing.JComboBox<String> cmbxUf;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblCelular;
    private javax.swing.JLabel lblCep;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblCnpj;
    private javax.swing.JLabel lblComplemento;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNomeFornecedor;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUf;
    private javax.swing.JPanel pnlConsultaFornecedores;
    private javax.swing.JPanel pnlDadosFornecedores;
    private javax.swing.JPanel pnlGeral;
    private javax.swing.JPanel pnlTitle;
    private javax.swing.JScrollPane scrollPaneDadosFornecedores;
    private javax.swing.JTabbedPane tabbedPaneFornecedores;
    private javax.swing.JTable tblDadosFornecedores;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtCep;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtCnpj;
    private javax.swing.JTextField txtComplemento;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNomeFornecedor;
    private javax.swing.JTextField txtNumero;
    // End of variables declaration//GEN-END:variables

    public void listarTodosFornecedores() {
        try {
            FornecedoresDao dao = new FornecedoresDao();
            ArrayList<Fornecedores> lista = dao.listarFornecedores();

            DefaultTableModel modelo = (DefaultTableModel) tblDadosFornecedores.getModel();
            modelo.setRowCount(0);

            for (Fornecedores f : lista) {
                modelo.addRow(new Object[]{
                    f.getId(),
                    f.getNome(),
                    f.getEmail(),
                    f.getCnpj(),
                    f.getCep(),
                    f.getEndereco(),
                    f.getNumero(),
                    f.getBairro(),
                    f.getCidade(),
                    f.getUnidade(),
                    f.getCelular()
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao listar fornecedores: " + e.getMessage());
        }
    }

}