package view;

import beans.Sorvetes;
import dao.SorvetesDao;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class TelaControleEstoque extends javax.swing.JFrame {

    public TelaControleEstoque() {
        initComponents();
        listarTodosSorvetes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlGeral = new javax.swing.JPanel();
        pnlTitle = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblSaborSorvete = new javax.swing.JLabel();
        txtSaborSorvete = new javax.swing.JTextField();
        btnPesquisarSorvetes = new javax.swing.JButton();
        pnlListaSorvetes = new javax.swing.JPanel();
        scrollPaneListaSorvetes = new javax.swing.JScrollPane();
        tblListaSorvetes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlGeral.setBackground(new java.awt.Color(248, 248, 255));
        pnlGeral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlTitle.setBackground(new java.awt.Color(215, 189, 226));

        lblTitle.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Controle de Estoque");

        javax.swing.GroupLayout pnlTitleLayout = new javax.swing.GroupLayout(pnlTitle);
        pnlTitle.setLayout(pnlTitleLayout);
        pnlTitleLayout.setHorizontalGroup(
            pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 684, Short.MAX_VALUE)
        );
        pnlTitleLayout.setVerticalGroup(
            pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTitleLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblTitle)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pnlGeral.add(pnlTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lblSaborSorvete.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblSaborSorvete.setText("Sabor do sorvete:");
        pnlGeral.add(lblSaborSorvete, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        txtSaborSorvete.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pnlGeral.add(txtSaborSorvete, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 180, -1));

        btnPesquisarSorvetes.setBackground(new java.awt.Color(255, 218, 185));
        btnPesquisarSorvetes.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnPesquisarSorvetes.setText("Pesquisar");
        btnPesquisarSorvetes.setToolTipText("Clique aqui para pesquisar os sorvetes");
        btnPesquisarSorvetes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarSorvetesActionPerformed(evt);
            }
        });
        pnlGeral.add(btnPesquisarSorvetes, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 104, -1));

        pnlListaSorvetes.setBackground(new java.awt.Color(248, 248, 255));
        pnlListaSorvetes.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista de sorvetes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 16))); // NOI18N

        tblListaSorvetes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Sorvete", "Categoria", "Preço", "Unidade", "Quantidade", "Fornecedor", "Entrada", "Validade"
            }
        ));
        scrollPaneListaSorvetes.setViewportView(tblListaSorvetes);

        javax.swing.GroupLayout pnlListaSorvetesLayout = new javax.swing.GroupLayout(pnlListaSorvetes);
        pnlListaSorvetes.setLayout(pnlListaSorvetesLayout);
        pnlListaSorvetesLayout.setHorizontalGroup(
            pnlListaSorvetesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListaSorvetesLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(scrollPaneListaSorvetes, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        pnlListaSorvetesLayout.setVerticalGroup(
            pnlListaSorvetesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListaSorvetesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPaneListaSorvetes, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pnlGeral.add(pnlListaSorvetes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, 270));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlGeral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlGeral, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisarSorvetesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarSorvetesActionPerformed
        try {
            // Pega o sabor digitado no jTextField
            String sabor = txtSaborSorvete.getText().trim();

            // Buscando os sorvetes pelo sabor
            SorvetesDao dao = new SorvetesDao();
            ArrayList<Sorvetes> lista = dao.listarSorvetesPorSabor(sabor);

            // Atualiza a tabela com os resultados encontrados
            DefaultTableModel modelo = (DefaultTableModel) tblListaSorvetes.getModel();
            modelo.setRowCount(0);

            for (Sorvetes s : lista) {
                modelo.addRow(new Object[]{
                    s.getId(),
                    s.getSaborSorvete(),
                    s.getCategoria(),
                    s.getPreco(),
                    s.getUnidade(),
                    s.getQuantidade(),
                    s.getFornecedor().getNome(),
                    s.getDataEntrada(),
                    s.getDataValidade()
                });
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao pesquisar sorvete: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnPesquisarSorvetesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaControleEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaControleEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaControleEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaControleEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaControleEstoque().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPesquisarSorvetes;
    private javax.swing.JLabel lblSaborSorvete;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlGeral;
    private javax.swing.JPanel pnlListaSorvetes;
    private javax.swing.JPanel pnlTitle;
    private javax.swing.JScrollPane scrollPaneListaSorvetes;
    private javax.swing.JTable tblListaSorvetes;
    private javax.swing.JTextField txtSaborSorvete;
    // End of variables declaration//GEN-END:variables

    public void listarTodosSorvetes() {
        try {
            SorvetesDao dao = new SorvetesDao();
            ArrayList<Sorvetes> lista = dao.listarSorvetes();

            DefaultTableModel modelo = (DefaultTableModel) tblListaSorvetes.getModel();
            modelo.setRowCount(0);

            for (Sorvetes s : lista) {
                modelo.addRow(new Object[]{
                    s.getId(),
                    s.getSaborSorvete(),
                    s.getCategoria(),
                    s.getPreco(),
                    s.getUnidade(),
                    s.getQuantidade(),
                    s.getFornecedor().getNome(),
                    s.getDataEntrada(),
                    s.getDataValidade()
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao listar sorvetes: " + e.getMessage());
        }
    }

}
