package view;

import beans.Vendas;
import dao.VendasDao;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class TelaHistoricoVendas extends javax.swing.JFrame {

    /**
     * Creates new form TelaHistoricoVendas
     */
    public TelaHistoricoVendas() {
        initComponents();
        listarTodasVendas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlGeral = new javax.swing.JPanel();
        pnlTitle = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        pnlConsultaData = new javax.swing.JPanel();
        lblDataInicio = new javax.swing.JLabel();
        lblDataFinal = new javax.swing.JLabel();
        btnPesquisarVendas = new javax.swing.JButton();
        scrollPaneVendas = new javax.swing.JScrollPane();
        tblVendas = new javax.swing.JTable();
        formattedTxtDataInicio = new javax.swing.JFormattedTextField();
        formattedTxtDataFinal = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlGeral.setBackground(new java.awt.Color(248, 248, 255));
        pnlGeral.setLayout(new java.awt.GridBagLayout());

        pnlTitle.setBackground(new java.awt.Color(215, 189, 226));

        lblTitle.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Histórico de Vendas");

        javax.swing.GroupLayout pnlTitleLayout = new javax.swing.GroupLayout(pnlTitle);
        pnlTitle.setLayout(pnlTitleLayout);
        pnlTitleLayout.setHorizontalGroup(
            pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlTitleLayout.setVerticalGroup(
            pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTitleLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblTitle)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 480;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        pnlGeral.add(pnlTitle, gridBagConstraints);

        pnlConsultaData.setBackground(new java.awt.Color(248, 248, 255));
        pnlConsultaData.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Consulta por data", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 16))); // NOI18N
        pnlConsultaData.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDataInicio.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblDataInicio.setText("Data de início:");
        pnlConsultaData.add(lblDataInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 55, -1, -1));

        lblDataFinal.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblDataFinal.setText("Data final:");
        pnlConsultaData.add(lblDataFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 55, -1, -1));

        btnPesquisarVendas.setBackground(new java.awt.Color(255, 218, 185));
        btnPesquisarVendas.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnPesquisarVendas.setText("Pesquisar");
        btnPesquisarVendas.setToolTipText("Clique aqui para pesquisar as vendas feitas");
        btnPesquisarVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarVendasActionPerformed(evt);
            }
        });
        pnlConsultaData.add(btnPesquisarVendas, new org.netbeans.lib.awtextra.AbsoluteConstraints(535, 52, 104, -1));

        tblVendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Id sorvete", "Quantidade(s)", "Pagamento", "Data e hora", "Valor total"
            }
        ));
        scrollPaneVendas.setViewportView(tblVendas);

        pnlConsultaData.add(scrollPaneVendas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 610, 250));

        try {
            formattedTxtDataInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        formattedTxtDataInicio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        formattedTxtDataInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formattedTxtDataInicioActionPerformed(evt);
            }
        });
        pnlConsultaData.add(formattedTxtDataInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 53, 120, -1));

        try {
            formattedTxtDataFinal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        formattedTxtDataFinal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        formattedTxtDataFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formattedTxtDataFinalActionPerformed(evt);
            }
        });
        pnlConsultaData.add(formattedTxtDataFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 53, 120, -1));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 30;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        pnlGeral.add(pnlConsultaData, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlGeral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlGeral, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formattedTxtDataFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formattedTxtDataFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formattedTxtDataFinalActionPerformed

    private void formattedTxtDataInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formattedTxtDataInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formattedTxtDataInicioActionPerformed

    private void btnPesquisarVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarVendasActionPerformed
        try {
            // Pega as datas dos JTextFields
            String textoDataInicio = formattedTxtDataInicio.getText().trim();
            String textoDataFim = formattedTxtDataFinal.getText().trim();

            // Converte as datas para LocalDateTime
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            LocalDateTime dataInicio = LocalDate.parse(textoDataInicio, formatter).atStartOfDay();
            LocalDateTime dataFim = LocalDate.parse(textoDataFim, formatter).atTime(23, 59, 59);

            // Consulta as vendas no período
            VendasDao dao = new VendasDao();
            ArrayList<Vendas> lista = dao.consultarVendasPeriodo(dataInicio, dataFim);

            // Atualiza a tabela com os resultados encontrados
            DefaultTableModel modelo = (DefaultTableModel) tblVendas.getModel();
            modelo.setRowCount(0); // limpa a tabela

            for (Vendas v : lista) {
                modelo.addRow(new Object[]{
                    v.getId(),
                    v.getIdSorvete(),
                    v.getQuantidadeSorvete(),
                    v.getFormaPagamento(),
                    v.getDataHoraVenda().format(DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm")),
                    v.getValorTotal()
                });
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao pesquisar vendas por período: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnPesquisarVendasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaHistoricoVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaHistoricoVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaHistoricoVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaHistoricoVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaHistoricoVendas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPesquisarVendas;
    private javax.swing.JFormattedTextField formattedTxtDataFinal;
    private javax.swing.JFormattedTextField formattedTxtDataInicio;
    private javax.swing.JLabel lblDataFinal;
    private javax.swing.JLabel lblDataInicio;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlConsultaData;
    private javax.swing.JPanel pnlGeral;
    private javax.swing.JPanel pnlTitle;
    private javax.swing.JScrollPane scrollPaneVendas;
    private javax.swing.JTable tblVendas;
    // End of variables declaration//GEN-END:variables

    public void listarTodasVendas() {
        try {
            VendasDao dao = new VendasDao();
            ArrayList<Vendas> lista = dao.listarVendas();

            DefaultTableModel modelo = (DefaultTableModel) tblVendas.getModel();
            modelo.setRowCount(0);

            for (Vendas v : lista) {
                modelo.addRow(new Object[]{
                    v.getId(),
                    v.getIdSorvete(),
                    v.getQuantidadeSorvete(),
                    v.getFormaPagamento(),
                    v.getDataHoraVenda().format(DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm")),
                    v.getValorTotal()
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao listar clientes: " + e.getMessage());
        }
    }
}
