package view;

import beans.Usuario;
import dao.ImagensDao;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class TelaInicial extends javax.swing.JFrame {

    private Usuario usuarioAutenticado;
    
    public TelaInicial(Usuario u) {
        initComponents();
        this.usuarioAutenticado = u;
        
        ImagensDao desktop = new ImagensDao();
        desktop.setBounds(pnlDesktopTelaInicial.getBounds());
        this.remove(pnlDesktopTelaInicial);
        this.add(desktop);
        this.repaint();

        if (u.getTipo().equalsIgnoreCase("Gerente")) {
            menuClientes.setEnabled(true);
            menuFuncionarios.setEnabled(true);
            menuFornecedores.setEnabled(true);
            menuProdutos.setEnabled(true);
            menuVendas.setEnabled(true);
            menuConfiguracoes.setEnabled(true);
            menuSair.setEnabled(true);
        } else if (u.getTipo().equalsIgnoreCase("Vendedor")) {
            menuFuncionarios.setEnabled(false);
            menuFornecedores.setEnabled(false);
            menuItemControleEstoque.setEnabled(false);
            menuItemHistoricoVendas.setEnabled(false);
            menuConfiguracoes.setEnabled(true);
            menuSair.setEnabled(true);
        }
    }

    public TelaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDesktopTelaInicial = new javax.swing.JDesktopPane();
        menuBarMenuSistema = new javax.swing.JMenuBar();
        menuClientes = new javax.swing.JMenu();
        menuItemClientes = new javax.swing.JMenuItem();
        menuFuncionarios = new javax.swing.JMenu();
        menuItemFuncionarios = new javax.swing.JMenuItem();
        menuFornecedores = new javax.swing.JMenu();
        menuItemFornecedores = new javax.swing.JMenuItem();
        menuProdutos = new javax.swing.JMenu();
        menuItemProdutos = new javax.swing.JMenuItem();
        menuItemControleEstoque = new javax.swing.JMenuItem();
        menuVendas = new javax.swing.JMenu();
        menuVendasInternal = new javax.swing.JMenu();
        menuItemCadastroVendas = new javax.swing.JMenuItem();
        menuItemHistoricoVendas = new javax.swing.JMenuItem();
        menuConfiguracoes = new javax.swing.JMenu();
        menuItemMudarConta = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenu();
        menuItemSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlDesktopTelaInicial.setBackground(new java.awt.Color(248, 248, 255));

        javax.swing.GroupLayout pnlDesktopTelaInicialLayout = new javax.swing.GroupLayout(pnlDesktopTelaInicial);
        pnlDesktopTelaInicial.setLayout(pnlDesktopTelaInicialLayout);
        pnlDesktopTelaInicialLayout.setHorizontalGroup(
            pnlDesktopTelaInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 698, Short.MAX_VALUE)
        );
        pnlDesktopTelaInicialLayout.setVerticalGroup(
            pnlDesktopTelaInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 362, Short.MAX_VALUE)
        );

        getContentPane().add(pnlDesktopTelaInicial, java.awt.BorderLayout.CENTER);

        menuBarMenuSistema.setBackground(new java.awt.Color(215, 189, 226));
        menuBarMenuSistema.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        menuBarMenuSistema.setOpaque(true);

        menuClientes.setText("Clientes");
        menuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClientesActionPerformed(evt);
            }
        });

        menuItemClientes.setText("Área de clientes");
        menuItemClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuItemClientesMouseClicked(evt);
            }
        });
        menuItemClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemClientesActionPerformed(evt);
            }
        });
        menuClientes.add(menuItemClientes);

        menuBarMenuSistema.add(menuClientes);

        menuFuncionarios.setText("Funcionários");

        menuItemFuncionarios.setText("Área de funcionários");
        menuItemFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemFuncionariosActionPerformed(evt);
            }
        });
        menuFuncionarios.add(menuItemFuncionarios);

        menuBarMenuSistema.add(menuFuncionarios);

        menuFornecedores.setText("Fornecedores");

        menuItemFornecedores.setText("Área de fornecedores");
        menuItemFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemFornecedoresActionPerformed(evt);
            }
        });
        menuFornecedores.add(menuItemFornecedores);

        menuBarMenuSistema.add(menuFornecedores);

        menuProdutos.setText("Produtos");

        menuItemProdutos.setText("Área de produtos");
        menuItemProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuItemProdutosMouseClicked(evt);
            }
        });
        menuItemProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemProdutosActionPerformed(evt);
            }
        });
        menuProdutos.add(menuItemProdutos);

        menuItemControleEstoque.setText("Controle de estoque");
        menuItemControleEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemControleEstoqueActionPerformed(evt);
            }
        });
        menuProdutos.add(menuItemControleEstoque);

        menuBarMenuSistema.add(menuProdutos);

        menuVendas.setText("Vendas");

        menuVendasInternal.setText("Área de vendas");

        menuItemCadastroVendas.setText("Cadastro de vendas");
        menuItemCadastroVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCadastroVendasActionPerformed(evt);
            }
        });
        menuVendasInternal.add(menuItemCadastroVendas);

        menuItemHistoricoVendas.setText("Histórico de vendas");
        menuItemHistoricoVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemHistoricoVendasActionPerformed(evt);
            }
        });
        menuVendasInternal.add(menuItemHistoricoVendas);

        menuVendas.add(menuVendasInternal);

        menuBarMenuSistema.add(menuVendas);

        menuConfiguracoes.setText("Configurações");
        menuConfiguracoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConfiguracoesActionPerformed(evt);
            }
        });

        menuItemMudarConta.setText("Mudar de conta");
        menuItemMudarConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemMudarContaActionPerformed(evt);
            }
        });
        menuConfiguracoes.add(menuItemMudarConta);

        menuBarMenuSistema.add(menuConfiguracoes);

        menuSair.setText("Sair");
        menuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSairActionPerformed(evt);
            }
        });

        menuItemSair.setText("Sair do sistema");
        menuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSairActionPerformed(evt);
            }
        });
        menuSair.add(menuItemSair);

        menuBarMenuSistema.add(menuSair);

        setJMenuBar(menuBarMenuSistema);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClientesActionPerformed

    }//GEN-LAST:event_menuClientesActionPerformed

    private void menuItemClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemClientesActionPerformed
        TelaClientes tc = new TelaClientes();
        tc.setVisible(true);
    }//GEN-LAST:event_menuItemClientesActionPerformed

    private void menuItemFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemFuncionariosActionPerformed
        TelaFuncionarios tf = new TelaFuncionarios();
        tf.setVisible(true);
    }//GEN-LAST:event_menuItemFuncionariosActionPerformed

    private void menuItemFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemFornecedoresActionPerformed
        TelaFornecedores tf = new TelaFornecedores();
        tf.setVisible(true);
    }//GEN-LAST:event_menuItemFornecedoresActionPerformed

    private void menuItemProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemProdutosActionPerformed
        TelaProdutos tp = new TelaProdutos();
        tp.setVisible(true);
    }//GEN-LAST:event_menuItemProdutosActionPerformed

    private void menuItemCadastroVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCadastroVendasActionPerformed
        TelaVendas tv = new TelaVendas();
        tv.setVisible(true);
    }//GEN-LAST:event_menuItemCadastroVendasActionPerformed

    private void menuItemHistoricoVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemHistoricoVendasActionPerformed
        TelaHistoricoVendas thv = new TelaHistoricoVendas();
        thv.setVisible(true);
    }//GEN-LAST:event_menuItemHistoricoVendasActionPerformed

    private void menuItemControleEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemControleEstoqueActionPerformed
        TelaControleEstoque tce = new TelaControleEstoque();
        tce.setVisible(true);
    }//GEN-LAST:event_menuItemControleEstoqueActionPerformed

    private void menuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSairActionPerformed

    }//GEN-LAST:event_menuSairActionPerformed

    private void menuConfiguracoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConfiguracoesActionPerformed

    }//GEN-LAST:event_menuConfiguracoesActionPerformed

    private void menuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSairActionPerformed
        Object[] opcoes = {"Sim, sair", "Não, cancelar"};

        int resposta = JOptionPane.showOptionDialog(this, "Tem certeza que deseja encerrar o sistema?", "Confirmação",
                JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE, null, opcoes, opcoes[1]);

        if (resposta == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_menuItemSairActionPerformed

    private void menuItemMudarContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemMudarContaActionPerformed
        int confirmacao = JOptionPane.showConfirmDialog(this, "Deseja realmente sair da conta atual?",
                "Trocar de Conta", JOptionPane.YES_NO_OPTION);

        if (confirmacao == JOptionPane.YES_OPTION) {
            this.dispose();

            TelaLogin tl = new TelaLogin();
            tl.setVisible(true);
        }
    }//GEN-LAST:event_menuItemMudarContaActionPerformed

    private void menuItemClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuItemClientesMouseClicked

    }//GEN-LAST:event_menuItemClientesMouseClicked

    private void menuItemProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuItemProdutosMouseClicked

    }//GEN-LAST:event_menuItemProdutosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar menuBarMenuSistema;
    private javax.swing.JMenu menuClientes;
    private javax.swing.JMenu menuConfiguracoes;
    private javax.swing.JMenu menuFornecedores;
    private javax.swing.JMenu menuFuncionarios;
    private javax.swing.JMenuItem menuItemCadastroVendas;
    private javax.swing.JMenuItem menuItemClientes;
    private javax.swing.JMenuItem menuItemControleEstoque;
    private javax.swing.JMenuItem menuItemFornecedores;
    private javax.swing.JMenuItem menuItemFuncionarios;
    private javax.swing.JMenuItem menuItemHistoricoVendas;
    private javax.swing.JMenuItem menuItemMudarConta;
    private javax.swing.JMenuItem menuItemProdutos;
    private javax.swing.JMenuItem menuItemSair;
    private javax.swing.JMenu menuProdutos;
    private javax.swing.JMenu menuSair;
    private javax.swing.JMenu menuVendas;
    private javax.swing.JMenu menuVendasInternal;
    private javax.swing.JDesktopPane pnlDesktopTelaInicial;
    // End of variables declaration//GEN-END:variables
}
